import cv2
import numpy as np
kernel = np.ones((5, 5), np.uint8)
resim = cv2.imread("vcd.png")
dilate = cv2.dilate(resim, kernel, iterations=1)
erode = cv2.erode(resim, kernel)
opening = cv2.morphologyEx(resim, cv2.MORPH_OPEN, kernel)
closoing = cv2.morphologyEx(resim, cv2.MORPH_CLOSE, kernel)
blachat = cv2.morphologyEx(resim, cv2.MORPH_BLACKHAT, kernel)
tophat = cv2.morphologyEx(resim, cv2.MORPH_TOPHAT, kernel)
cv2.imshow("resim", resim)
cv2.imshow("tophat", tophat)
cv2.imshow("opening", opening)
cv2.imshow("dilate", dilate)
cv2.imshow("erode", erode)
cv2.imshow("close", closoing)
cv2.imshow("blachat", blachat)
cv2.waitKey(0)
cv2.destroyAllWindows()
